biblioteka/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include

urlpatterns +=[
	path('katalog/',include('katalog.urls')),
]

from django.views.generic import RedirectView

urlpatterns +=[
	path('',RedirectView.as_view(url='/katalog/')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

katalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('',views.index, name='index'),
	path('ksiazki/',views.KsiazkaListView.as_view(), name='ksiazki'),
	path('autorzy/',views.AutorListView.as_view(), name='autorzy'),
	path('ksiazka/<int:pk>',views.KsiazkaSzczegolView.as_view(),name='ksiazka-detail'),
]

katalog/models.py
from django.db import models
from django.urls import reverse
import uuid 
# Create your models here.
class Gatunek(models.Model):
	nazwa = models.CharField(max_length=200, help_text="Gatunek, kategoria (np. poezja, fantastyka)")
	def __str__(self):
		return self.nazwa

class Ksiazka(models.Model):
	tytul = models.CharField(max_length=200)
	autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True, help_text='Autor tej ksiazki')
	opis = models.TextField(max_length=1000, help_text='Opis ksiazki')
	isbn = models.CharField('ISBN', max_length = 13, help_text='<a href="https://www.isbn-international.org/content/what-isbn">ISBN</a>')
	gatunek = models.ManyToManyField(Gatunek, help_text='Gatunek tej ksiazki')


	def __str__(self):
		return self.tytul

	def get_absolute_url(self):
		return reverse('ksiazka-detail', args=[str(self.id)])
	
	def display_gatunek(self):
		return ', '.join([ gatunek.nazwa for gatunek in self.gatunek.all()[:3] ])
		display_gatunek.short_description = 'Gat.'

from django.contrib.auth.models import User

class InstancjaKsiazki(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID tej ksiazki")
	ksiazka = models.ForeignKey('Ksiazka', on_delete=models.SET_NULL, null=True)
	wydawca = models.CharField(max_length=200)
	data_zwrotu = models.DateField(null=True, blank=True)
	wypozycza = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

	STATUS_WYPOZYCZENIA = (
		('n','Naprawa'),
		('w','Wypozyczona'),
		('d','Dostepna'),
		('z','Zarezerwowana'),
	)

	status = models.CharField(max_length=1, choices=STATUS_WYPOZYCZENIA, blank=True, default='n', help_text='Dostepnosc ksiazki')
	
	class Meta:
		ordering = ['data_zwrotu']

	def __str__(self):
		return '{0} ({1})'.format(self.id, self.ksiazka.tytul)

class Autor(models.Model):
	imie = models.CharField(max_length=100)
	nazwisko = models.CharField(max_length=100)
	data_urodzenia = models.DateField(null=True, blank=True)
	data_smierci = models.DateField('Zmarl', null=True, blank=True)
	class Meta:
		ordering = ["nazwisko","imie"]
	def get_absolute_url(self):
		return reverse('autor-detail', args=[str(self.id)])

	def __str__(self):
		return '{0}, {1}'.format(self.nazwisko, self.imie)

katalog/views.py
from django.shortcuts import render

# Create your views here.

from .models import Autor, Gatunek, Ksiazka, InstancjaKsiazki

def index(request):
	num_ks=Ksiazka.objects.all().count()
	num_in=InstancjaKsiazki.objects.all().count()
	num_in_d=InstancjaKsiazki.objects.filter(status__exact='d').count()
	num_au=Autor.objects.count()
	
	return render(
		request,
		'index.html',
		context={'num_ks':num_ks,'num_in':num_in,'num_in_d':num_in_d,'num_au':num_au}
	)


from django.views import generic

class AutorListView(generic.ListView):
	model = Autor

class KsiazkaListView(generic.ListView):
	model = Ksiazka
	context_object_name = 'moja_ksiazka_list'
	#queryset = Ksiazka.objects.filter(tytul__icontains =' ')[:5]
	template_name = 'katalog/ksiazka_moja_list.html'
	paginate_by = 3
class KsiazkaSzczegolView(generic.DetailView):
	model = Ksiazka

katalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %} <title> Biblioteka </title> {% endblock %}
	<meta charset="utf-8>
	<meta name="viewport" content="width=devise.width, inital_scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script scr="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/boostrap.min.js"></script>
	
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-2">
			{% block sidebar %}
			<ul class="sidebar-nav">
				<li><a href="{% url 'index' %}"> Strona glowna </a></li>
				<li><a href="{% url 'ksiazki' %}"> Ksiazki </a></li>
				<li><a href="{% url 'autorzy' %}"> Autorzy</a></li>
			</ul>
			{% endblock %}
			</div>
			<div class="col-sm-10">
			{% block content %}{%endblock%}
			{% block pagination %}
				{% if is_paginated %}
					<div class = "pagination">
						<span class="page-links">
							{%if page_obj.has_previous %}
								<a href="{{ request.path }}?page={{page_obj.previous_page_number }}">poprzednia </a>
							{% endif %}
							<span class="page-current">
								Strona {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
							</span>
							{% if page_obj.has_next %}
								<a href="{{request.path}}?page={{page_obj.next_page_number}}">Nastepna</a>
							{% endif %}
						</span>
					</div>
				{% endif %}
			{% endblock %}
			</div>
		</div>
	</div>
</body>
	

katalog/templates/index.html
{% extends "base_generic.html"%}
{% block content %}
<h1> Strona domowa - Biblioteka </h1>

	<p> Witaj! </p>
	
<h2> Informacje </h2>
	<p> Zawartosc biblioteki </p>
	<ul>
		<li><strong>Ksiazki:</strong> {{num_ks}}</li>
		<li><strong>Egzemplarze:</strong> {{num_in}}</li>
		<li><strong>Egzemplarze dostepne:</strong> {{num_in_d}}</li>
		<li><strong>Autorzy:</strong> {{num_au}}</li>
	</ul>
{% endblock %}

katalog/templates/katalog/autor_list.html
{% extends "base_generic.html"%}
{% block content %}
<h1> lista autorow </h1>
	{% if autor_list %}
	<ul>
		{% for autor in autor_list %}
		<li>
			{{autor.nazwisko}}
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<p> Jeszcze nie mamy zadnych autorow </p>
	{% endif %}
{% endblock %}

katalog/templates/katalog/ksiazka_detail.html
{% extends "base_generic.html" %}

{% block content %}
	<h1> Tytul: {{ksiazka.tytul}}</h1>
	
	<p><strong>Autor:</strong> {{ ksiazka.autor}} </p>
	<p><strong>Opis:</strong> {{ ksiazka.opis}} </p>
	<p><strong>ISBN:</strong> {{ ksiazka.isbn}} </p>
	<p><strong>Gatunek:</strong> {% for g in ksiazka.gatunek.all %} {{g}} {% if not forloop.last %},{% endif %} {% endfor %} </p>
	<div style="margin-left:20px;margin-top:20px">
	<h4>Egzemplarze</h4>
	{% for inst in ksiazka.instancjaksiazki_set.all %}
	<hr>
	<p class= "{% if inst.status == 'd' %}text-success{% elif inst.status == 'n' %}text-danger{% else %} text-warning{% endif %}"> {{inst.get_status_display}} </p>
	{% if inst.status != 'd' and inst.status != 'n' %}
		<p> <strong> Data zwrotu: </strong> {{inst.data_zwrotu}} </p>
	{% endif %}
	<p> <strong> Wydawca: </strong> {{inst.wydawca}} </p>
	<p class="text-muted"><strong> Id:</strong> {{inst.id}} </p>
	{% endfor %}
</div>
{% endblock %}

katalog/templates/katalog/ksiazka_moja_list.html
{% extends "base_generic.html"%}

{% block content %}

<h1> lista ksiazek </h1>
	{% if moja_ksiazka_list %}
	<ul>
		{% for k in moja_ksiazka_list %}
		<li>
		<a href = "{{ k.get_absolute_url}}"> {{k.tytul}} </a> ({{k.autor}})
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<p> Jeszcze nie mamy zadnych ksiazek </p>
	{% endif %}
{% endblock %}